baseURL = "https://electronsutra.github.io/immaculacy/"
languageCode = "en-us"
title = "Immaculacy"

[params]
BookTheme = "auto"
BookRepo = "https://github.com/ElectronSutra/immaculacy"
BookComments = false

[markup.goldmark.renderer]
unsafe = true
